# to install opencv for use by tensorflow (may not be necessary):
# 'mkdir -p /config/deps/lib/python3.7/site-packages/'
# 'pip install -t /config/deps/lib/python3.7/site-packages/ opencv-python'

- platform: tensorflow
  source:
    - entity_id: camera.porch
  file_out:
    - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_latest.jpg"
    # - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
    categories:
      - person
      - cat
      - dog
- platform: tensorflow
  source:
    - entity_id: camera.pool
  file_out:
    - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_latest.jpg"
    # - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
    categories:
      - person
      - cat
      - dog
- platform: tensorflow
  source:
    - entity_id: camera.front
  file_out:
    - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_latest.jpg"
    # - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
    categories:
      - person
      - cat
      - dog
- platform: tensorflow
  source:
    - entity_id: camera.basement
  file_out:
    - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_latest.jpg"
    # - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
    categories:
      - person
      - cat
      - dog
    # area:
    #   bottom: 0.9
    #   left: 0
- platform: tensorflow
  source:
    - entity_id: camera.driveway
  file_out:
    - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_latest.jpg"
    # - "/config/www/tensorflow/snapshot/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  scan_interval: 604800
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
    categories:
      - person
      - cat
      - dog
      - car
      - truck
      - motorcycle
      - bicycle