  - platform: darksky
    name: Weather
    api_key: !secret darksky-api_key
    forecast:
      - 0
    monitored_conditions:
      - summary
      - nearest_storm_distance
      - precip_intensity
      - precip_probability
      - temperature
      - temperature_high
      - temperature_low
      - wind_speed
      - wind_bearing
      - visibility
      - apparent_temperature
      - minutely_summary
      - hourly_summary
      - daily_summary
      - dew_point
      - cloud_cover
      - humidity
  # - platform: xfinity
  #   username: !secret xfinity_email
  #   password: !secret xfinity_password
  - platform: filter
    name: "Weather Wind Speed (Filtered)"
    entity_id: sensor.weather_wind_speed
    filters:
        - filter: outlier
          window_size: 4
          radius: 6.0
        - filter: lowpass
          time_constant: 3
          precision: 2
  - platform: filter
    name: "Smartweather Brightness (Filtered)"
    entity_id: sensor.smartweather_brightness
    filters:
      # - filter: outlier
      #   window_size: 4
      #   radius: 6.0
      - filter: lowpass
        time_constant: 5
        precision: 0
      # - filter: time_simple_moving_average
      #   window_size: 00:15
      #   precision: 0

  - platform: command_line
    name: "Blue Iris Profile"
    command: "python3 /config/shell/getBIProfile.py"
  - platform: template
    sensors:
      jeff_home_status:
        friendly_name: 'Jeff Home Status'
        value_template: "{{is_state('device_tracker.jeffs_xs_tracker','home') or (is_state('device_tracker.jeffsphone','home') and is_state('device_tracker.jeffs_phone_2','home'))}}"
  - platform: template
    sensors:
      jen_home_status:
        friendly_name: 'Jen Home Status'
        value_template: "{{is_state('device_tracker.jennifers_xs_max_tracker','home') or (is_state('device_tracker.jennifers_xs_max','home') and is_state('device_tracker.jennifersxsmax','home'))}}"
  - platform: template
    sensors:
      ansley_home_status:
        friendly_name: 'Ansley Home Status'
        value_template: "{{is_state('device_tracker.ansleys_xr_tracker','home') or (is_state('device_tracker.eye_phone','home') and is_state('device_tracker.ansleys_xr_2','home'))}}"
  - platform: template
    sensors:
      brinley_home_status:
        friendly_name: 'Brinley Home Status'
        value_template: "{{(is_state('device_tracker.brinleythebest','home') and is_state('device_tracker.brinleythebest_2','home'))}}"
  - platform: template
    sensors:
      anyone_home:
        friendly_name: 'Home Status'
        # value_template: "{% if is_state('sensor.jeff_home_status', 'True') or is_state('sensor.jen_home_status', 'True') or is_state('sensor.ansley_home_status', 'True')-%}home{%else%}not_home{% endif %}"
        value_template: "{% if is_state('group.family', 'home')-%}home{%else%}not_home{% endif %}"
  - platform: template
    sensors:
      garage_status:
        friendly_name: 'Jeff''s garage door status'
        value_template: '{% if states.cover.jeff_garage_door %}
            {% if states.cover.jeff_garage_door.attributes["door_state"] == "open" %}
              Open
            {% elif states.cover.jeff_garage_door.attributes["door_state"] == "closed" %}
              Closed
            {% elif states.cover.jeff_garage_door.attributes["door_state"] == "opening" %}
              Opening
            {% elif states.cover.jeff_garage_door.attributes["door_state"] == "closing" %}
              Closing
            {% elif states.cover.jeff_garage_door.attributes["door_state"] == "offline" %}
              Offline
            {% else %}
              Unknown
            {% endif %}
            {% else %}
            n/a
            {% endif %}'
      garage_car_present:
        friendly_name: 'Jeff''s car in garage'
        value_template: '{% if states.cover.jeff_garage_door %}
            {% if states.cover.jeff_garage_door.state == "open" %}
              n/a
            {% elif ((states.cover.jeff_garage_door.attributes["distance_sensor"] > 40) and (states.cover.jeff_garage_door.attributes["distance_sensor"] < 130)) %}
              Yes
            {% else %}
              No
            {% endif %}
            {% else %}
            n/a
            {% endif %}'
      garage2_status:
        friendly_name: 'Jen''s garage door status'
        value_template: '{% if states.cover.jen_garage_door %}
            {% if states.cover.jen_garage_door.attributes["door_state"] == "open" %}
              Open
            {% elif states.cover.jen_garage_door.attributes["door_state"] == "closed" %}
              Closed
            {% elif states.cover.jen_garage_door.attributes["door_state"] == "opening" %}
              Opening
            {% elif states.cover.jen_garage_door.attributes["door_state"] == "closing" %}
              Closing
            {% elif states.cover.jen_garage_door.attributes["door_state"] == "offline" %}
              Offline
            {% else %}
              Unknown
            {% endif %}
            {% else %}
            n/a
            {% endif %}'
      garage2_car_present:
        friendly_name: 'Jen''s car in garage'
        value_template: '{% if states.cover.jen_garage_door %}
            {% if states.cover.jen_garage_door.state == "open" %}
              n/a
            {% elif ((states.cover.jen_garage_door.attributes["distance_sensor"] > 40) and (states.cover.jen_garage_door.attributes["distance_sensor"] < 130)) %}
              Yes
            {% else %}
              No
            {% endif %}
            {% else %}
            n/a
            {% endif %}'
  - platform: template
    sensors:
      alarm_status:
        friendly_name: 'Alarm Status'
        value_template: "{% if is_state('sensor.alarm_panel_display', 'ARMED ***AWAY***** ALL SECURE **') or is_state('sensor.alarm_panel_display', 'ARMED ***STAY***                ') or is_state('sensor.alarm_panel_display', '***NIGHT-STAY***                ') %}Armed{%else%}Disarmed{% endif %}"

### teslamate
  - platform: mqtt
    name: tesla_battery_level
    state_topic: "teslamate/cars/1/battery_level"
    unit_of_measurement: '%'
    icon: mdi:battery-80

  - platform: mqtt
    name: tesla_charge_energy_added
    state_topic: "teslamate/cars/1/charge_energy_added"
    unit_of_measurement: 'kW'
    icon: mdi:battery-80

  - platform: mqtt
    name: tesla_charge_limit
    state_topic: "teslamate/cars/1/charge_limit_soc"
    unit_of_measurement: '%'
    icon: mdi:battery-80

  - platform: mqtt
    name: tesla_charge_port_door_open
    state_topic: "teslamate/cars/1/charge_port_door_open"
    icon: mdi:car-door

  - platform: mqtt
    name: tesla_charger_actual_current
    state_topic: "teslamate/cars/1/charger_actual_current"
    unit_of_measurement: 'A'
    icon: mdi:battery-80

  - platform: mqtt
    name: tesla_charger_phases
    state_topic: "teslamate/cars/1/charger_phases"
    icon: mdi:power-plug

  - platform: mqtt
    name: tesla_charger_power
    state_topic: "teslamate/cars/1/charger_power"
    unit_of_measurement: 'W'
    icon: mdi:power-plug

  - platform: mqtt
    name: tesla_charger_voltage
    state_topic: "teslamate/cars/1/charger_voltage"
    unit_of_measurement: 'V'
    icon: mdi:gauge

  - platform: mqtt
    name: tesla_display_name
    state_topic: "teslamate/cars/1/display_name"
    icon: mdi:car

  - platform: mqtt
    name: tesla_estimated_range
    state_topic: "teslamate/cars/1/est_battery_range_km"
    unit_of_measurement: 'km'
    icon: mdi:map-marker-path

  - platform: mqtt
    name: tesla_healthy
    state_topic: "teslamate/cars/1/healthy"
    icon: mdi:car-connected

  - platform: mqtt
    name: tesla_ideal_range
    state_topic: "teslamate/cars/1/ideal_battery_range_km"
    unit_of_measurement: 'km'
    icon: mdi:map-marker-path

  - platform: mqtt
    name: tesla_inside_temp
    state_topic: "teslamate/cars/1/inside_temp"
    unit_of_measurement: °C
    icon: mdi:thermometer-lines

  - platform: mqtt
    name: tesla_latitude
    state_topic: "teslamate/cars/1/latitude"
    icon: mdi:crosshairs-gps

  - platform: mqtt
    name: tesla_locked
    state_topic: "teslamate/cars/1/locked"
    icon: mdi:lock

  - platform: mqtt
    name: tesla_longitude
    state_topic: "teslamate/cars/1/longitude"
    icon: mdi:crosshairs-gps

  - platform: mqtt
    name: tesla_odometer
    state_topic: "teslamate/cars/1/odometer"
    unit_of_measurement: km
    icon: mdi:gauge

  - platform: mqtt
    name: tesla_outside_temp
    state_topic: "teslamate/cars/1/outside_temp"
    unit_of_measurement: °C
    icon: mdi:thermometer-lines

  - platform: template
    sensors:
      tesla_park_brake:
        friendly_name: Park Brake
        value_template: >-
          {% if is_state('sensor.tesla_shift_state', 'P') %}
            true
          {% else %}
            false
          {% endif %}

  - platform: mqtt
    name: tesla_plugged_in
    state_topic: "teslamate/cars/1/plugged_in"
    icon: mdi:power-plug

  - platform: mqtt
    name: tesla_rated_range
    state_topic: "teslamate/cars/1/rated_battery_range_km"
    unit_of_measurement: 'km'
    icon: mdi:map-marker-path

  - platform: mqtt
    name: tesla_scheduled_charging_start
    state_topic: "teslamate/cars/1/scheduled_charging_start_time"
    icon: mdi:clock-outline

  - platform: mqtt
    name: tesla_sentry_mode
    state_topic: "teslamate/cars/1/sentry_mode"
    icon: mdi:cctv

  - platform: mqtt
    name: tesla_shift_state
    state_topic: "teslamate/cars/1/shift_state"
    icon: mdi:car-shift-pattern

  - platform: mqtt
    name: tesla_speed
    state_topic: "teslamate/cars/1/speed"
    icon: mdi:speedometer

  - platform: mqtt
    name: tesla_state
    state_topic: "teslamate/cars/1/state"
    icon: mdi:car-connected

  - platform: mqtt
    name: tesla_time_to_full_charge
    state_topic: "teslamate/cars/1/time_to_full_charge"
    icon: mdi:clock-outline

  - platform: mqtt
    name: tesla_windows_open
    state_topic: "teslamate/cars/1/windows_open"
    icon: mdi:car-door

  - platform: mqtt
    name: tesla_version
    state_topic: "teslamate/cars/1/version"
    icon: mdi:alphabetical

  - platform: mqtt
    name: tesla_update_available
    state_topic: "teslamate/cars/1/update_available"
    icon: mdi:gift
