- name: Home
  latitude: !env_var LATITUDE
  longitude: !env_var LONGITUDE
  radius: 200
  icon: mdi:home

- name: Work
  latitude: !env_var WORK_LATITUDE
  longitude: !env_var WORK_LONGITUDE
  radius: 100
  icon: mdi:office-building

- name: Jens Work
  latitude: !env_var JENS_WORK_LATITUDE
  longitude: !env_var JENS_WORK_LONGITUDE
  radius: 100
  icon: mdi:briefcase

- name: SSC
  latitude: !env_var SSC_LATITUDE
  longitude: !env_var SSC_LONGITUDE
  radius: 100
  icon: mdi:office-building