######################################################################################################
### Automations related to setting the Blue Iris profile for various states
###
######################################################################################################

#### Core automation to execute shell script to set BI profile based on what's selected on the input_select
#### all other "set bi profile" automations only change the input_select to the desired BI profile

- alias: BlueIris - Set BI profile when input select changes
  trigger:
    platform: state
    entity_id: input_select.set_biprofile
  action:
    service: shell_command.set_bi_profile

#### Set BI profile to "alert" if a door or garage door opens while we are not home
# - alias: 'BlueIris - Set BI profile to alert if doors open while we are not home'
#   trigger:
#     - platform: state
#       entity_id: group.doors_windows
#       to: open
#   condition:
#     condition: state
#     entity_id: group.presence
#     state: 'not_home'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: input_select.set_biprofile
#         option: 'alert'

#### Set BI profile to 'day' at sunrise and 'alert_night' at night
# - alias: BlueIris - Set BI profile to morning/night when home
#   trigger:
#     - platform: sun
#       event: 'sunrise'
#     - platform: time
#       at: '22:00'
#   condition:
#     condition: state
#     entity_id: sensor.anyone_home
#     state: 'home'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: input_select.set_biprofile
#         option: "{{ 'alert_night' if trigger.now.time().hour == 22 else 'day' }}"

#### Set BI profile to 'alert_day_wind' if we're not home and it is windy during the day
#### Set BI profile to 'alert_day' if we're not home and it is not windy during the day
- alias: BlueIris - Set BI profile to alert_day/alert_day_windy when not home and wind speed > 5mph
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 5
  condition:
    condition: and
    conditions:
      - condition: sun
        after: 'sunrise'
        after_offset: "01:00:00"
      - condition: sun
        before: 'sunset'
        before_offset: "-01:00:00"
      - condition: state
        entity_id: sensor.anyone_home
        state: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: "{{ 'alert_day_windy' if states('sensor.weather_wind_speed') | float > 5 else 'alert_day' }}"




#### Set BI profile to 'day_wind' if we're home and it is windy during the day
#### Set BI profile to 'day' if we're home and it is not windy during the day
- alias: BlueIris - Set BI profile to day/day_windy when home and wind speed > 5mph
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 5
  condition:
    condition: and
    conditions:
      - condition: sun
        after: 'sunrise'
        after_offset: "01:00:00"
      - condition: sun
        before: 'sunset'
        before_offset: "-01:00:00"
      - condition: state
        entity_id: sensor.anyone_home
        state: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: "{{ 'day_windy' if states('sensor.weather_wind_speed') | float > 5 else 'day' }}"

#### Set BI profile to 'alert_night' at 10pm if we're home
- alias: BlueIris - Set BI profile to alert_night when home at 10pm
  trigger:
    - platform: time
      at: '22:00'
  condition:
    condition: state
    entity_id: sensor.anyone_home
    state: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'alert_night'

#### Notify is BI profile gets set to 'unknown'
- alias: BlueIris - Notify if BI profile is 'unknown'
  trigger:
    platform: state
    entity_id: sensor.blueiris_profile
    to: 'unknown'
  action:
    service: notify.slack
    data:
      message: "BI profile switched to 'unknown'"
