- id: alert_when_everyone_leaves_home
  alias: 'Alert when everyone leaves home'
  trigger:
    platform: state
    entity_id: sensor.anyone_home
    to: 'not_home'
  action:
    - service: notify.ios_jeff_phone
      data_template:
        title: "Presence"
        message: "Everyone has left home"
- id: alert_when_anyone_comes_home
  alias: 'Alert when anyone comes home'
  trigger:
    platform: state
    entity_id: sensor.anyone_home
    to: 'home'
  action:
    - service: notify.ios_jeff_phone
      data_template:
        title: "Presence"
        message: "Someone came home"


- alias: Presence - Set BI day when we get home
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'home'
  condition:
    condition: sun
    after: 'sunrise'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'day'

- alias: Presence - Set BI alert_day when we leave
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'not_home'
  condition:
    condition: sun
    after: 'sunrise'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'alert_day'

- alias: Presence - Set BI night when we get home before 10pm
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: 'sunset'
      - condition: time
        before: '22:00'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'night'

- alias: Presence - Set BI alert_night when we get home after 10pm
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: 'sunset'
      - condition: time
        after: '22:00'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'alert_night'

- alias: Presence - Set BI alert_night when we leave
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'not_home'
  condition:
    condition: sun
    after: 'sunset'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'alert_night'
