################################################################################
## Set BI profile when we leave or come home
################################################################################
- id: set_bi_home_when_home 
  alias: BI home when we get home
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'home'
  condition:
    condition: sun
    after: sunrise
    after_offset: "00:30:00"
    before: sunset
    before_offset: "-00:30:00"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'home'

- id: set_bi_away_when_leave 
  alias: BI away when we leave
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'not_home'
  condition:
    condition: sun
    after: sunrise
    after_offset: "00:30:00"
    before: sunset
    before_offset: "-00:30:00"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'away'

- id: set_bi_away_when_leave_after_sunset
  alias: BI away when we leave after sunset
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'not_home'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'away'

- id: set_bi_home_when_home_before_10pm 
  alias: BI night when we get home before 10pm
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.anyone_home
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: time
        before: '22:00:00'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_biprofile
        option: 'home'


# - alias: Ansley Occupancy On
#   initial_state: on
# #   hide_entity: true
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.ansley_s_phone_bluetooth_occupancy_confidence
#       above: 10
#   action:
#     - service: homeassistant.turn_on
#       data:
#         entity_id: input_boolean.ansley_occupancy

# - alias: Ansley Occupancy Off
#   initial_state: on
# #   hide_entity: true
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.ansley_s_phone_bluetooth_occupancy_confidence
#       below: 10
#   action:
#     - service: homeassistant.turn_off
#       data:
#         entity_id: input_boolean.ansley_occupancy

################################################################################
## ESPrescense for custom device_trackers
################################################################################

# jeff
- alias: "jeff phone espresense"
  trigger:
  - platform: state
    entity_id: sensor.jeff_phone
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.jeff_phone
        state: 'not_home'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/espresense_jeffsphone
          payload: 'not_home'
    default:
      - service: mqtt.publish
        data:
          topic: location/espresense_jeffsphone
          payload: 'home'

- alias: "jeff watch espresense"
  trigger:
  - platform: state
    entity_id: sensor.jeff_watch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.jeff_watch
        state: 'not_home'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/espresense_jeffswatch
          payload: 'not_home'
    default:
      - service: mqtt.publish
        data:
          topic: location/espresense_jeffswatch
          payload: 'home'

# jen
- alias: "jen phone espresense"
  trigger:
  - platform: state
    entity_id: sensor.jen_phone
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.jen_phone
        state: 'not_home'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/espresense_jensphone
          payload: 'not_home'
    default:
      - service: mqtt.publish
        data:
          topic: location/espresense_jensphone
          payload: 'home'

- alias: "jen watch espresense"
  trigger:
  - platform: state
    entity_id: sensor.jen_watch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.jen_watch
        state: 'not_home'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/espresense_jenswatch
          payload: 'not_home'
    default:
      - service: mqtt.publish
        data:
          topic: location/espresense_jenswatch
          payload: 'home'

# ansley
- alias: "ansley phone espresense"
  trigger:
  - platform: state
    entity_id: sensor.ansley_phone
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.ansley_phone
        state: 'not_home'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/espresense_ansleysphone
          payload: 'not_home'
    default:
      - service: mqtt.publish
        data:
          topic: location/espresense_ansleysphone
          payload: 'home'

- alias: "ansley watch espresense"
  trigger:
  - platform: state
    entity_id: sensor.ansley_watch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.ansley_watch
        state: 'not_home'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/espresense_ansleyswatch
          payload: 'not_home'
    default:
      - service: mqtt.publish
        data:
          topic: location/espresense_ansleyswatch
          payload: 'home'

# brinley
- alias: "brinley phone espresense"
  trigger:
  - platform: state
    entity_id: sensor.brinley_phone
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.brinley_phone
        state: 'not_home'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/espresense_brinleysphone
          payload: 'not_home'
    default:
      - service: mqtt.publish
        data:
          topic: location/espresense_brinleysphone
          payload: 'home'
