- alias: Update Tesla location as MQTT location updates
  initial_state: on
  trigger:
    - platform: mqtt
      topic: teslamate/cars/1/latitude
    - platform: mqtt
      topic: teslamate/cars/1/longitude
  action:
    - service: device_tracker.see
      data_template:
        dev_id: tesla_location
        location_name: not_home
        gps: [ '{{ states.sensor.tesla_latitude.state }}', '{{ states.sensor.tesla_longitude.state }}' ]


# - alias: Wake TeslaMate on Garage Open
#   initial_state: on
#   trigger:
#     - platform: state
#       entity_id: switch.garage_door_switch
#       to: 'off'
#   action:
#     - service: script.turn_on
#       entity_id: script.wake_teslamate
