- platform: mjpeg
  mjpeg_url: http://10.0.7.13:81/mjpg/driveway
  name: driveway
  username: !secret bi_user
  password: !secret bi_pass
  authentication: basic
- platform: mqtt
  name: Driveway Camera Last Person
  topic: frigate/driveway/person/snapshot