- platform: mjpeg
  mjpeg_url: http://10.0.7.13:81/mjpg/front
  name: front
  username: !secret bi_user
  password: !secret bi_pass
  authentication: basic
- platform: mqtt
  name: Front Camera Last Person
  topic: frigate/front/person/snapshot