- platform: mjpeg
  mjpeg_url: http://10.0.7.13:81/mjpg/porch
  name: porch
  username: !secret bi_user
  password:  !secret bi_pass
  authentication: basic
- platform: mqtt
  name: Porch Camera Last Person
  topic: frigate/porch/person/snapshot